### ISSUE TITLE
解析特别慢

### ISSUE THREAD

**Issue by abxm2** [myxuchangbin/dnsmasq_sniproxy_install#11]
遇到一个问题，运行2个月后，解析的非常慢。不知道是时间长的问题，还是连接数/缓存什么的问题。重启dnsmasq/sniproxy/重装脚本都不能解决，最后重装了系统，然后装脚本恢复正常。不知道是什么原因？

**Comment by myxuchangbin** [comment]
我对dnsmasq配置文件稍微做了优化，你可以再测试一下

**Comment by myxuchangbin** [comment]
问一下是解析流媒体网站慢还是解析其他网站也慢？

**Comment by wulimaxh** [comment]
解析非流媒体网站很慢，加载网页非常慢。流媒体的没有试，我猜也是很慢

**Comment by myxuchangbin** [comment]
你可以按我刚修改的试一下
