### ISSUE TITLE
请问下我如果想添加FOX+(foxplus.com)的代理，应如何修改配置文件？

### ISSUE THREAD

**Issue by liunice** [myxuchangbin/dnsmasq_sniproxy_install#17]
首先说明一下，FOX+需要香港、台湾或新加坡的IP才可访问。我是有台香港的主机可以用来做代理的。
我尝试着修改了/etc/dnsmasq.d/custom_netflix.conf和/etc/sniproxy.conf，参照其他域名的样子，添加了对foxplus.com这个域名的解析，但最终好像没生效。

能指教一下应如何添加吗？多谢了！

**Comment by myxuchangbin** [comment]
在/etc/dnsmasq.d/custom_netflix.conf最后一行添加：
`address=/foxpus.com/vpsip`
在/etc/sniproxy.conf `table { }`中添加：
`.*foxpus\.com$ *`
然后重启dnsmasq、sniproxy

**Comment by liunice** [comment]
address=/foxpus.com/vpsip 这一行怎么和上面的不一样？因为我看上面每行都有一个IP来结尾。。。
我按你的要求把这行添加进去后，restart dnsmasq后报错了，提示如下：
Oct 21 01:25:38 instance-tw dnsmasq[11122]: dnsmasq: bad address at line 91 of /etc/dnsmasq.d/custom_netflix.conf
Oct 21 01:25:38 instance-tw dnsmasq[11122]: bad address at line 91 of /etc/dnsmasq.d/custom_netflix.conf
Oct 21 01:25:38 instance-tw dnsmasq[11122]: FAILED to start up
Oct 21 01:25:38 instance-tw systemd[1]: dnsmasq.service: Control process exited, code=exited status=1
Oct 21 01:25:38 instance-tw systemd[1]: Failed to start dnsmasq - A lightweight DHCP and caching DNS server.
Oct 21 01:25:38 instance-tw systemd[1]: dnsmasq.service: Unit entered failed state.
Oct 21 01:25:38 instance-tw systemd[1]: dnsmasq.service: Failed with result 'exit-code'.

提示错误在91行，也就是我刚添加的这一行。。。

**Comment by liunice** [comment]
@myxuchangbin 错误信息在上面，还麻烦您帮忙看一下是什么原因，谢谢了！

**Comment by liunice** [comment]
@myxuchangbin 多谢，我来试试！
PS：上面的foxpus你写错了哈，应该是foxplus

**Comment by liunice** [comment]
@myxuchangbin 按您的方法设置后，现在fox+的APP能进去了，但是播放视频时 提示所在地区不支持，我猜测 除了foxpus.com的域名以外，这个APP在播放时还使用了其他的域名？
想请教下有没有什么办法可以知道这个播放器用的什么域名？有什么技术手段可以检测吗？

PS： 我的香港原生IP的VPS主机，单独运行v2ray时是可以正常观看以上的视频的，说明我的香港IP没有问题。现在的问题应该是出在域名没有完全覆盖的问题上。只是猜测。

**Comment by myxuchangbin** [comment]
具体查看哪个域名可以用抓包工具获取到，大概搜了一下，Fox+可能需要以下3个域名：
foxplus.com
theplatform.com
akamaized.net

参考自：https://github.com/lhie1/Rules/blob/master/Surge3/Media/FoxPlus.list

**Comment by liunice** [comment]
@myxuchangbin 多谢，看来我少了akamaized.net这个域名。晚点我再试试

**Comment by liunice** [comment]
@myxuchangbin 我刚发现你提到的akamaized.net这个可能缺失的域名在两个配置文件中本来就已经有了，所以没必要再重复添加一次。

然后，我刚发现一个有趣的现象。我用nslookup命令检查像hulu.com, netflix.com这样的需要走DNS的域名，命令执行的结果都是有期望的结果，即域名下面的那个IP都是显示的DNS服务器的IP，如下方所示(hulu.com下面的那个IP)：
[root@cheery-win-1 ~]# nslookup hulu.com
Server:		34.80.122.217
Address:	34.80.122.217#53

Name:	hulu.com
Address: 34.80.122.217


然而，问题来了，所以我去nslookup foxplus.com呢，出来的结果明显和其它域名的不一样，如下：
[root@cheery-win-1 ~]# nslookup foxplus.com
Server:		34.80.122.217
Address:	34.80.122.217#53

Non-authoritative answer:
Name:	foxplus.com
Address: 52.85.83.220
Name:	foxplus.com
Address: 52.85.83.50
Name:	foxplus.com
Address: 52.85.83.88
Name:	foxplus.com
Address: 52.85.83.129

可疑点主要在从Non-authoritative answer 这一行开始的，foxplus.com下面那一行的IP，好像直接就是它对应的真实IP，跟上面hulu.com显示的不一样。。。

这倒底是哪里出了问题？我已经在DNS服务器（34.80.122.217）的两个配置文件里加上 foxplus.com的配置了。

求指教，谢谢！

**Comment by liunice** [comment]
@myxuchangbin 我刚发现你提到的akamaized.net这个可能缺失的域名在两个配置文件中本来就已经有了，所以没必要再重复添加一次。

【以下假设我的DNS服务器IP为1.2.3.4】

然后，我刚发现一个有趣的现象。我用nslookup命令检查像hulu.com, netflix.com这样的需要走DNS的域名，命令执行的结果都是有期望的结果，即域名下面的那个IP都是显示的DNS服务器的IP，如下方所示(hulu.com下面的那个IP)：
[root@cheery-win-1 ~]# nslookup hulu.com
Server: 1.2.3.4
Address: 1.2.3.4#53

Name: hulu.com
Address: 1.2.3.4

然而，问题来了，所以我去nslookup foxplus.com呢，出来的结果明显和其它域名的不一样，如下：
[root@cheery-win-1 ~]# nslookup foxplus.com
Server: 1.2.3.4
Address: 1.2.3.4#53

Non-authoritative answer:
Name: foxplus.com
Address: 52.85.83.220
Name: foxplus.com
Address: 52.85.83.50
Name: foxplus.com
Address: 52.85.83.88
Name: foxplus.com
Address: 52.85.83.129

可疑点主要在从Non-authoritative answer 这一行开始的，foxplus.com下面那一行的IP，好像直接就是它对应的真实IP，跟上面hulu.com显示的不一样。。。

这倒底是哪里出了问题？我已经在DNS服务器（1.2.3.4）的两个配置文件里加上 foxplus.com的配置了。

求指教，谢谢！

**Comment by liunice** [comment]
@myxuchangbin 上面四个52开头的IP，我随便挑了其中两个IP，用nslookup反向查询了一下得到其域名，发现是cloudfront公司的，cloudfront好像是类似cloudflare的一个防ddos的网站？（不是我专业，不太懂）

[root@cheery-win-1 ~]# nslookup 52.85.83.50
50.83.85.52.in-addr.arpa	name = server-52-85-83-50.lax1.r.cloudfront.net.

Authoritative answers can be found from:

[root@cheery-win-1 ~]# nslookup 52.85.83.129
129.83.85.52.in-addr.arpa	name = server-52-85-83-129.lax1.r.cloudfront.net.

Authoritative answers can be found from:


也许DNS反向代理失败的原因就在于这个cloudfront？仅仅是我的猜测。供参考。

**Comment by myxuchangbin** [comment]
你把电脑的dns1和dns2都改成你的vpsIP，再测试一下
还可以使用nslookup foxplus.com DNSIP 来指定dns服务器查看解析
另外还是看一下配置文件中的域名是否正确

**Comment by liunice** [comment]
@myxuchangbin
1. DNS都改了VPSIP了，没用
2. nslookup foxplus.com DNSIP返回结果：
nslookup foxplus.com 103.209.102.42
Server:		103.209.102.42
Address:	103.209.102.42#53

Non-authoritative answer:
Name:	foxplus.com
Address: 52.85.83.129
Name:	foxplus.com
Address: 52.85.83.50
Name:	foxplus.com
Address: 52.85.83.220
Name:	foxplus.com
Address: 52.85.83.88

===================
同样有下面那一长段Non-authoritative answer。

3. 配置文件反复检查了，真的没有配错。。。

**Comment by myxuchangbin** [comment]
清除一下dns缓存试一下
windows命令：ipconfig /flushdns

**Comment by liunice** [comment]
@myxuchangbin 每次都会清缓存的。

问个小问题，你觉得这个跟FOX+所使用的cloudfront CDN没有关系吗？

**Comment by myxuchangbin** [comment]
和用哪个CDN没有关系，现在的情况是DNS服务器没有解析出指定IP

**Comment by liunice** [comment]
@myxuchangbin 首先感谢你的耐心解答，经过几天的折腾，目前我算是基本解决了这个问题。结论如下：

1、跑科学上网的VPS不能使用v2ray + websocket + tls，我之前一直用的这个协议，结果一直不行。今天试着换成shadowsocksr，结果居然可以了。另外没有测试普通的v2ray(TCP)协议，我估计应该也可以。

2、/etc/resolv.conf文件里要把你的代理DNS IP 放在最上面。我之前其实有一段时间是同时配置了两个，一个DNS IP 用来代理hulu.com，另外一个用来代理foxplus.com，我以为可以平行配置两个的（这应该算是我最大的一个误解）。今天索性把DNS IP改成只有一个（可以代理foxplus.com的那个），于是就可以了。

其实我原来想实现的功能是：在源VPS（客户端连接的VPS）上同时能代理hulu.com和foxplus.com，所有hulu.com的流量导向DNS 1，foxplus.com的流量导向DNS 2。现在发现用你的组件好像实现不了，你的组件好像是把所有IP段的请求全部转发给了最前面那一个DNS。google上查了一下，要实现有选择性地代理，需要用到一种叫GRE Tunnel的技术？（参考https://oogami.name/1560/） 
不太懂。。。有时间我可能会继续研究一下。。。折腾啊。。。

总之，谢谢你开发这样的项目！辛苦了！

**Comment by myxuchangbin** [comment]
1、v2ray有一个设置自定义dns的地方，可能他没有走你的dns服务器，可以参考：https://www.v2ray.com/chapter_02/04_dns.html
2、关于这种情况你可以只安装一个dnsmasq，也就是一个dns服务器，然后将解析记录分别设置成各自IP就可以了
3、你可以研究一下各代理软件的域名分流功能

**Comment by liunice** [comment]
@myxuchangbin 实在太感谢了，看到你说的第2题关于dnsmasq的，我一下子恍然大悟，感觉之前浪费了不少时间，瞎折腾了。下午在原VPS上装了dnsmasq，然后在dnsmasq.conf里配置了类似server=/foxplus.com/DNSIP这样的语法，实现了把FOX+, Netflix, Hulu分别指向不同的DNS服务器，最终全部代理成功，这个实现太简洁了！

昨天其实也大致实现了，用的是redsocket+tinyproxy+ipset+iptables的方法，虽然能用，但明显速度特别慢，不知道咋回事。今天用你说的dnsmasq分流以后，速度正常了，体验很不错！

总之，感谢了！这次折腾一番，也不学到了不少网络知识，什么ipset, iptabes...感觉网络这一块还需要好好补习一番啊！

**Comment by xiaocai1234** [comment]
谢谢大大了！刚上车一个Fox+。这些域名老有用了。走SSR的Netflix分流。
