### ISSUE TITLE
能让sniproxy监听8080或者8443端口吗

### ISSUE THREAD

**Issue by shengshengman0** [myxuchangbin/dnsmasq_sniproxy_install#19]
一台能看NF的小鸡，但是先前的默认设置占用了443和80端口，我通过修改/etc/sniproxy.conf的配置文件，把80和443相应改成8080和8443，重启sniproxy,发现解锁不了NF（可以说明下原因吗？），443和80想留给TROJAN和V2RAY

**Comment by myxuchangbin** [comment]
如果修改端口的话，你访问Netflix的时候就需要加上端口了，例如www.netflix.com:8443，这时不排除某些情况下Netflix网站会跳转到原默认端口，导致无法访问。

**Comment by shengshengman0** [comment]
> 如果修改端口的话，你访问Netflix的时候就需要加上端口了，例如www.netflix.com:8443，这时不排除某些情况下Netflix网站会跳转到原默认端口，导致无法访问。
那这样的话，还是不换端口比较好
