### ISSUE TITLE
在能看netflix的小鸡上部署？

### ISSUE THREAD

**Issue by rdstwg** [myxuchangbin/dnsmasq_sniproxy_install#2]
在能看netflix的小鸡上部署？然后修改不能看Netflix的小鸡的dns吗？我修改了但是并没有用大佬求教

**Comment by SaylerYang** [comment]
是的 在能看的小鸡上部署 然后改不能看的小鸡的dns 可以把dns改成一个
顺便问下 这个同时要转发流量吗？

**Comment by myxuchangbin** [comment]
只在不能看的小鸡上修改DNS就可以了，不用做流量转发。
如果没有用，将DNS只保留一个试一下，必须两个的话那就两个都填同一个
