### ISSUE TITLE
一键安装之后安装的VPS的酸酸乳好像无法使用

### ISSUE THREAD

**Issue by abclai** [myxuchangbin/dnsmasq_sniproxy_install#21]
你好，我是个菜鸟了！

一键安装你的脚本之前，用酸酸乳测试过NF可以看啦

但是安装之后酸酸乳就无法连通成功啦，不知道是为何，可否脚本可否和酸酸乳兼容？

还是安装之后酸酸乳就不能使用？尝试重新安装过秋水的酸酸乳也是一样无法使用

不清楚是否不兼容啦

**Comment by myxuchangbin** [comment]
只要端口不冲突，是完全兼容的
