### ISSUE TITLE
安装失败求助

### ISSUE THREAD

**Issue by ANHR0** [myxuchangbin/dnsmasq_sniproxy_install#22]
![安装失败](https://user-images.githubusercontent.com/49902303/76422578-649c2400-63e0-11ea-803f-86231e589bf5.png)

**Comment by myxuchangbin** [comment]
系统版本说一下

**Comment by ANHR0** [comment]
centos7.5
![111](https://user-images.githubusercontent.com/49902303/76682724-6a407680-6639-11ea-8ed8-7c2cb1b0e895.png)

**Comment by myxuchangbin** [comment]
先运行一下命令：`yum groups mark remove development`，然后再运行脚本试试，后面我会更新脚本

**Comment by ANHR0** [comment]
多谢大佬，完美解决

**Comment by ANHR0** [comment]
想再请教下，如果用日本原生ip的机子，这个脚本能解锁abema.tv 之类的的吗？

**Comment by myxuchangbin** [comment]
理论上是可以解锁的，你要先确认IP可以观看abema.tv，然后确认abema.tv的相关域名在设置的域名列表中

**Comment by Scholar-m** [comment]
Bahamut设置好了以后

此网站无法提供安全连接ani.gamer.com.tw 使用了不受支持的协议。
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
协议不受支持
客户端和服务器不支持一般 SSL 协议版本或加密套件。

**Comment by myxuchangbin** [comment]
编辑文件`/etc/sniproxy.conf`，将12行的`mode ipv4_only`改成`mode ipv6_first`，再测试一下。

**Comment by Scholar-m** [comment]
还是不行
此网站无法提供安全连接ani.gamer.com.tw 使用了不受支持的协议。
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
协议不受支持
客户端和服务器不支持一般 SSL 协议版本或加密套件。

**Comment by myxuchangbin** [comment]
试着将配置改成`mode ipv4_first`，再测试一下。
参考问题：https://github.com/dlundquist/sniproxy/issues?q=ERR_SSL_VERSION_OR_CIPHER_MISMATCH
