### ISSUE TITLE
安装了连不上53端口

### ISSUE THREAD

**Issue by linkea131** [myxuchangbin/dnsmasq_sniproxy_install#29]
telnet: connect to address : Connection timed out 防火墙也关了

**Comment by myxuchangbin** [comment]
检查一下53端口是否有正常监听服务

**Comment by linkea131** [comment]
怎么检测

**Comment by linkea131** [comment]
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      2608/dnsmasq        
tcp6       0      0 :::53                   :::*                    LISTEN      2608/dnsmasq        
udp        0      0 0.0.0.0:53              0.0.0.0:*                           2608/dnsmasq        
udp6       0      0 :::53                   :::*                                2608/dnsmasq

**Comment by linkea131** [comment]
[Info] Starting to install package udns-devel
There is no installed groups file.
Maybe run: yum groups mark convert (see man yum)
有监听

**Comment by linkea131** [comment]
tcp 0 0 0.0.0.0:53 0.0.0.0:* LISTEN 2608/dnsmasq
tcp6 0 0 :::53 :::* LISTEN 2608/dnsmasq
udp 0 0 0.0.0.0:53 0.0.0.0:* 2608/dnsmasq
udp6 0 0 :::53 :::* 2608/dnsmasq
有监听 就是连不上
[Info] Starting to install package udns-devel
There is no installed groups file.
Maybe run: yum groups mark convert (see man yum)
这是安装时候提示的

**Comment by linkea131** [comment]
其他端口正常就53连不上

**Comment by myxuchangbin** [comment]
检查一下主机商是否有安全组未开放53端口

**Comment by linkea131** [comment]
开的0-65535不行吗

**Comment by linkea131** [comment]
可以了 主机商是否有安全组未开放
