### ISSUE TITLE
请问如果通过编辑配置文件，添加更多流媒体

### ISSUE THREAD

**Issue by yangyzp** [myxuchangbin/dnsmasq_sniproxy_install#3]
看文档介绍说可以添加更多流媒体。
但是不知道如果编辑配置文件，来添加其他流媒体。
求指教。

另外，请问一下，VPS（A）安装了这个脚本，其他VPS修改了dns后，看流媒体会跑VPS（A）的流量吗？

**Comment by myxuchangbin** [comment]
这里以添加域名amctv.com为例：
1. 编辑`/etc/dnsmasq.d/custom_netflix.conf`，将代码`address=/amctv.com/PublicIP`添加到最后一行（记得分行），将PublicIP替换为当前VPS的公网IP
2. 编辑`/etc/sniproxy.conf`，将代码`.*amctv\.com$ *`添加到`table`表中
同样一个域名占一行
上述配置皆可根据文件中已配置的Netflix来画瓢

目前SNIproxy是完整反代的流媒体网站，所以会跑VPS（A）的流量。PS：Netflix实测是这样的，其他还请自测一下吧

**Comment by CoolCollin** [comment]
请问能否不完整反代？ 只跑实际设置dns的vps B 的流量？ 请问如何设置呢

**Comment by myxuchangbin** [comment]
> 请问能否不完整反代？ 只跑实际设置dns的vps B 的流量？ 请问如何设置呢

配置文件中的域名想反代哪个就添加哪个，不反代哪个就删除哪个。不过我这边测试netflix必须完整反代才可以

**Comment by myxuchangbin** [comment]
已默认添加了更多流媒体。
