### ISSUE TITLE
[Error] Failed to install dnsmasq

### ISSUE THREAD

**Issue by rogellevi** [myxuchangbin/dnsmasq_sniproxy_install#32]
Hi.

in the installation this error throws me.

wget --no-check-certificate -O dnsmasq_sniproxy.sh https://raw.githubusercontent.com/myxuchangbin/dnsmasq_sniproxy_install/master/dnsmasq_sniproxy.sh && bash dnsmasq_sniproxy.sh -i

[Error] Failed to install dnsmasq

thks

**Comment by myxuchangbin** [comment]
You manually execute the command `yum install -y dnsmasq`
