### ISSUE TITLE
注释和重启命令

### ISSUE THREAD

**Issue by tandalin** [myxuchangbin/dnsmasq_sniproxy_install#34]
【注释】
sniproxy.conf和custom_netflix.conf能否添加注释？
分别怎么添加？
注释能包含中文吗？
---------------------
【重启命令】
sniproxy 和 dnsmasq的重启命令分别是？

**Comment by myxuchangbin** [comment]
用英文符号`#`来注释

**Comment by myxuchangbin** [comment]
重启命令分别是：`systemctl restart sniproxy` 和 `systemctl restart dnsmasq`
