### ISSUE TITLE
请问47704 的UDP端口是用来干什么的？

### ISSUE THREAD

**Issue by wnark** [myxuchangbin/dnsmasq_sniproxy_install#38]
![image](https://user-images.githubusercontent.com/24355466/89737412-593e4900-daa3-11ea-8be7-e443050434ca.png)
80he和443好理解，但47704端口有什么用呢？我搜了下源码也没专门说过47704的用途

**Comment by wnark** [comment]
又变成37133 ( UDP )了...

**Comment by myxuchangbin** [comment]
应该不是监听端口吧
