### ISSUE TITLE
请问可以在Ubuntu20上使用吗？

### ISSUE THREAD

**Issue by Sharkkkk** [myxuchangbin/dnsmasq_sniproxy_install#39]
报错：
Err:7 http://ppa.launchpad.net/dlundquist/sniproxy/ubuntu bionic Release                
  404  Not Found [IP: 2001:67c:1560:8008::15 80]
Reading package lists... Done                                
E: The repository 'http://ppa.launchpad.net/dlundquist/sniproxy/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by myxuchangbin** [comment]
在Ubuntu20上测试通过的，你的问题应该是添加了一个404的源：https://launchpad.net/~dlundquist/+archive/ubuntu/sniproxy
把这个源在`/etc/apt/sources.list.d/`这个目录下删掉，重新安装就可以了
