### ISSUE TITLE
无法代理

### ISSUE THREAD

**Issue by imswordman** [myxuchangbin/dnsmasq_sniproxy_install#4]
从另一个小鸡ping netflix返回是dns机的ip。确定dns机是可以看netflix的。
![pingtest](https://user-images.githubusercontent.com/50957648/58261682-5cb8b800-7dab-11e9-8e51-7858a8870281.png)

netflix提示检测到代理
![image](https://user-images.githubusercontent.com/50957648/58261475-f469d680-7daa-11e9-9afb-592099cfc0f8.png)

**Comment by myxuchangbin** [comment]
你是如何配置的dns呢？

**Comment by imswordman** [comment]
> 你是如何配置的dns呢？

centos7 Networkmanager.conf中dns=none 修改resolv.conf中的nameserver 为dns鸡的ip

**Comment by myxuchangbin** [comment]
你的代理软件有没有设置dns呢，还有你是用的哪个代理软件？

**Comment by imswordman** [comment]
> 你的代理软件有没有设置dns呢，还有你是用的哪个代理软件？

使用的CFW 设置了dns 尝试修改为dns鸡的ip还是用不了

**Comment by myxuchangbin** [comment]
你可能需要手动改一下代理软件的dns，并且保证dns保留一个，clash配置模板可以参考这里：
https://raw.githubusercontent.com/Hackl0us/SS-Rule-Snippet/master/LAZY_RULES/clash.yml

**Comment by imswordman** [comment]
> 你可能需要手动改一下代理软件的dns，并且保证dns保留一个，clash配置模板可以参考这里：
> https://raw.githubusercontent.com/Hackl0us/SS-Rule-Snippet/master/LAZY_RULES/clash.yml

改过了 nameserver和fallback都是dns鸡的ip 还是不行 照配置里所说netflix应该是采用fallback里的nameserver 我的fallback里只有dns鸡的ip 然后再进行尝试还是提示检测到代理 把iplocation也加入反代列表中 进行检测 还是显示的是我连接的那台鸡ip不是dns鸡的ip

**Comment by myxuchangbin** [comment]
目前问题应该是你的代理程序没有正确走你的dns鸡。

**Comment by imswordman** [comment]
> 目前问题应该是你的代理程序没有正确走你的dns鸡。

是的 找不到怎么去修改 尝试注释掉Clash的dns设置 还是没用 但是如果不连代理 直接设置电脑dns为dns鸡的ip 可以看netflix，然后又试了ssr进行连接 看日志里面写了
`[2019-05-25 15:28:31] [Info] DNS query ipv4-c192-lax001-ix.1.oca.nflxvideo.net answer *.*.*.*`
`[2019-05-25 15:28:31] [Info] DNS nolock query ipv4-c192-lax001-ix.1.oca.nflxvideo.net answer *.*.*.*`
返回的是那台dns鸡的ip 搞不清哪里出错了

**Comment by sunshine-rain-bow** [comment]
> 目前问题应该是你的代理程序没有正确走你的dns鸡。

额，把vps的DNS都设置成dns鸡了，不应该是所有的软件用dns鸡ip做解析的吗

**Comment by imswordman** [comment]
> 目前问题应该是你的代理程序没有正确走你的dns鸡。

现在测试使用以前配置文件观看nf正常，可能是前面cfw dns缓存了
