### ISSUE TITLE
现在脚本不能用了吗

### ISSUE THREAD

**Issue by bushizhangwudia** [myxuchangbin/dnsmasq_sniproxy_install#42]
''' 
Dnsmasq + SNI Proxy自助安装脚本
支持系统:  CentOS 6+, Debian8+, Ubuntu16+

检测您的系統...
[Info] Starting to install package net-tools
[Error] Failed to install net-tools 
'''

运行后出现这种问题 完全不知道哪里出错了 
debian 10 系统

**Comment by myxuchangbin** [comment]
你先执行一下`apt update`，然后继续执行脚本

**Comment by bushizhangwudia** [comment]
嗯 可以了
