### ISSUE TITLE
如果不占用80 443 53，改为支持非标准端口，就更好了

### ISSUE THREAD

**Issue by alexallen1** [myxuchangbin/dnsmasq_sniproxy_install#49]
我不知道可不可以改为非标准端口，但看网上教程清一色说要80 443 53
因为香港朋友家里软路由已经跑了其他服务，现在想跑个dnsmasq_sniproxy 让出80 443 53几乎不可能

**Comment by chuan01** [comment]
软路改端口不必这个香吗，

**Comment by myxuchangbin** [comment]
了解下逻辑原理你就知道为啥不能这么干了
