### ISSUE TITLE
我遇到了一个即使设置了能看NF的DNS，也会被提示proxy

### ISSUE THREAD

**Issue by sunshine-rain-bow** [myxuchangbin/dnsmasq_sniproxy_install#5]
![image](https://user-images.githubusercontent.com/50690914/58528251-73766900-8208-11e9-9f40-d09f883ce889.png)原因是这一个，但我无法解决啊，google上也没得

**Comment by sunshine-rain-bow** [comment]
aws的vps好像改了DNS也看不了NF

**Comment by myxuchangbin** [comment]
你的描述好像不太清楚，如果问题是`/etc/resolv.conf`文件一直被重置的话，可以看下面文档：
https://www.vultr.com/docs/stop-dhcp-from-changing-resolve-conf
推荐用这里面的第3个方法

**Comment by sunshine-rain-bow** [comment]
> 你的描述好像不太清楚，如果问题是`/etc/resolv.conf`文件一直被重置的话，可以看下面文档：
> https://www.vultr.com/docs/stop-dhcp-from-changing-resolve-conf
> 推荐用这里面的第3个方法

额，我是用chattr保护resolv.conf不被更改的
可我还是被提示proxy
vi /etc/resolv.conf修改成我那台能看NF机子的ip（修改好resolv.conf之后我没有重启机子），运行v2ray还是看不了

**Comment by myxuchangbin** [comment]
> > 你的描述好像不太清楚，如果问题是`/etc/resolv.conf`文件一直被重置的话，可以看下面文档：
> > https://www.vultr.com/docs/stop-dhcp-from-changing-resolve-conf
> > 推荐用这里面的第3个方法
> 
> 额，我是用chattr保护resolv.conf不被更改的
> 可我还是被提示proxy
> vi /etc/resolv.conf修改成我那台能看NF机子的ip（修改好resolv.conf之后我没有重启机子），运行v2ray还是看不了

**Comment by myxuchangbin** [comment]
最好的办法是修改下v2ray的dns配置：
https://www.v2ray.com/chapter_02/protocols/dns.html

**Comment by wansellbusiness** [comment]
在B机器上配置了Ａ机器ip作为ＤＮＳ服务器，在Ｂ机上ping netflix.com　也是Ａ机的ip，但看netflix视频时还是提示proxy
