### ISSUE TITLE
麻烦问下，除了指定网址，其他网址也走dns么

### ISSUE THREAD

**Issue by bbhxwl** [myxuchangbin/dnsmasq_sniproxy_install#51]
麻烦问下，除了指定网址，其他网址也走dns么。好像如果服务器关了，百度啥的也肯定打不开，有啥办法可以只让奈非走dns么。

**Comment by myxuchangbin** [comment]
这个需要你在本地去做规则了，一些代理客户端是都支持的

**Comment by jsjcjsjc** [comment]
感谢分享,有办法让sni proxy中转所有的流量吗?
感谢

**Comment by myxuchangbin** [comment]
这个问题建议考虑下其他的代理工具
