### ISSUE TITLE
流量是走哪里的？

### ISSUE THREAD

**Issue by rdstwg** [myxuchangbin/dnsmasq_sniproxy_install#6]
流量是走哪里的？看netflix小鸡上的嘛？

**Comment by hklkf** [comment]
看netflix小鸡上

**Comment by myxuchangbin** [comment]
中转鸡和落地鸡都走流量的。

**Comment by rdstwg** [comment]
也就是说2台机都走流量

**Comment by myxuchangbin** [comment]
> 也就是说看netflix时，2台机都走流量，其余不走？

你的意思还要走哪里的流量呢？

**Comment by ZBrettonYe** [comment]
我觉的他的意思是， 服务器A 看不了 NF， B 可以看。 用了基本后，A 可以看了。 A 看了1GB的NF视频，是A 和 B 都扣1GB流量 还是说，A 扣1GB流量， B就消耗一点点解析的流量

**Comment by myxuchangbin** [comment]
> 我觉的他的意思是， 服务器A 看不了 NF， B 可以看。 用了脚本后，A 可以看了。 A 看了1GB的NF视频，是A 和 B 各扣1GB流量 还是说，A 扣1GB流量， B就消耗一点点解析的流量

如果按你这个例子来说的话，两台都要走1G流量。
