### ISSUE TITLE
Debian 11无法安装

### ISSUE THREAD

**Issue by Pinkyou1** [myxuchangbin/dnsmasq_sniproxy_install#64]
请问Debian 11运行时出现以下错误，应如何解决？
[Error] Failed to install dnsmasq

**Comment by myxuchangbin** [comment]
手动执行`apt-get -y install dnsmasq` 看看是否报错

**Comment by Pinkyou1** [comment]
执行`apt-get -y install dnsmasq`正常安装

再次运行脚本出现 curl错误

[Info] Starting to install package curl
[Error] Failed to install curl

**Comment by myxuchangbin** [comment]
手动执行`apt-get -y install curl`，看一下报错信息
