### ISSUE TITLE
如何設定某ip才能連接

### ISSUE THREAD

**Issue by hklkf** [myxuchangbin/dnsmasq_sniproxy_install#7]
如何設定某ip才能連接

**Comment by myxuchangbin** [comment]
使用防火墙对IP做限制工作，防火墙软件大概有firewalld/iptables/ufw，具体使用方法google一下就可以了，很简单

**Comment by myxuchangbin** [comment]
某些主机商自带的安全组也可以用来限制IP

**Comment by mucunmjin** [comment]
iptables 能不能给个例子 谢谢

**Comment by mucunmjin** [comment]
-A INPUT -s 1.1.1.1/32 -p tcp -m tcp --dport 53 -j ACCEPT
-A INPUT -s 1.1.1.1/32 -p udp -m udp --dport 53 -j ACCEPT
-A INPUT -p udp -m udp --dport 53 -j DROP
-A INPUT -p tcp -m tcp --dport 53 -j DROP
