### ISSUE TITLE
强烈要求更新上chatgpt的域名规则

### ISSUE THREAD

**Issue by shinyboya** [myxuchangbin/dnsmasq_sniproxy_install#73]
大佬你好，我自己配置的chatgpt规则不生效。配置规则如下：

**Comment by shinyboya** [comment]
custom_netflix.conf加了
address=/platform.openai.com/35.78.119.28
address=/beta.openai.com/35.78.119.28
address=/auth0.openai.com/35.78.119.28
address=/auth1.openai.com/35.78.119.28
address=/auth2.openai.com/35.78.119.28
address=/openai.com/35.78.119.28


sniproxy.conf加了
table {
.*openai\.com$ *
}

**Comment by myxuchangbin** [comment]
已尝试增加openai域名，请测试

**Comment by shinyboya** [comment]
我现在测试

**Comment by shinyboya** [comment]
可以了大佬，大爱
