### ISSUE TITLE
检测端口占用的那块代码好像有点问题，53端口明明没占用，却判断为占用了

### ISSUE THREAD

**Issue by Buffer2Disk** [myxuchangbin/dnsmasq_sniproxy_install#8]
看了下应该是被模糊匹配了，53666 这种端口也被匹配到了，
可以改成这样的 
grep -P "\d+\.\d+\.\d+\.\d+:${aport} "  后面多个空格来精确匹配端口

**Comment by GQXXL** [comment]
重装 或者换一个系统

**Comment by myxuchangbin** [comment]
已修改，多谢反馈。
