### ISSUE TITLE
安装

### ISSUE THREAD

**Issue by GQXXL** [myxuchangbin/dnsmasq_sniproxy_install#9]
想问安装了这个，再去安装netflix proxy 是不是安装不了:(

**Comment by myxuchangbin** [comment]
netflix proxy也是安装了dnsmasq和sniproxy，同样会占用53,80,443端口，端口互相冲突，所以不能同时安装。

**Comment by GQXXL** [comment]
大佬，可以增加HULU hbo 等流媒体进去吗:)

**Comment by GQXXL** [comment]
> netflix proxy也是安裝了dnsmasq和sniproxy，同樣會佔用53,80,443端口，端口互相衝突，所以不能同時安裝。

大佬，可以增加HULU hbo等流媒體進去嗎:)

**Comment by myxuchangbin** [comment]
> 大佬，可以增加HULU hbo等流媒體進去嗎:)

已默认支持了更多的流媒体
